---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Minecraft Server using Docker"
Resources:
  MinecraftServerSec:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Minecraft Server Sec. Group"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: "tcp"
          FromPort: 25565
          ToPort: 25565
          CidrIp: 0.0.0.0/0
  MinecraftServerEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0453cb7b5f2b7fca2"
      InstanceType: "t2.medium"
      Tags:
        - Key: "Name"
          Value: "Minecraft Server"
      SecurityGroups:
        - !Ref MinecraftServerSec
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y && \
            yum install docker -y && \
            sudo service docker start && \
            sudo usermod -a -G docker ec2-user && \
            docker run -d -it -p 25565:25565 \
            -e EULA=TRUE \
            -e MODE=survival \
            -e restart=always \
            -e MOTD="-^^,--,~" \
            itzg/minecraft-server
